name: Publish Docs

on:
  push:
    branches: ['main']

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  publish-docs:
    name: Publish Docs to Github Pages
    needs: [build-and-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
